# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('stock_came', models.CharField(max_length=20, verbose_name='股票名称')),
                ('stock_lastPrice', models.FloatField(max_length=6, verbose_name='昨收')),
                ('stock_openprice', models.FloatField(max_length=6, verbose_name='今开')),
                ('stock_maxprice', models.FloatField(max_length=6, verbose_name='最高')),
                ('stock_minprice', models.FloatField(max_length=6, verbose_name='最低')),
                ('stock_dealqty', models.IntegerField(max_length=10, verbose_name='成交量/手')),
                ('stock_dealmoney', models.IntegerField(max_length=10, verbose_name='成交额/万')),
            ],
        ),
    ]
