# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_came',
            new_name='stock_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price',
            field=models.FloatField(default=0, max_length=6, verbose_name='当前价格'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_dealmoney',
            field=models.IntegerField(default=0, verbose_name='成交额/万'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_dealqty',
            field=models.IntegerField(default=0, verbose_name='成交量/手'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_lastPrice',
            field=models.FloatField(default=0, max_length=6, verbose_name='昨收'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_maxprice',
            field=models.FloatField(default=0, max_length=6, verbose_name='最高'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_minprice',
            field=models.FloatField(default=0, max_length=6, verbose_name='最低'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_openprice',
            field=models.FloatField(default=0, max_length=6, verbose_name='今开'),
        ),
    ]
