# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170911_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_dealmoney',
            field=models.BigIntegerField(default=0, verbose_name='成交额/万'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_dealqty',
            field=models.BigIntegerField(default=0, verbose_name='成交量/手'),
        ),
    ]
